### ISSUE TITLE
Remove `tape` from `dependencies`

### ISSUE THREAD

**Issue by ngryman** [HenrikJoreteg/key-tree-store#3]
Hi,

Related to my issue here: https://github.com/AmpersandJS/ampersand/issues/47
Could you only keep it in `devDependencies` so **browserify** won't bundle it?

Thanks!

**Comment by pgilad** [comment]
Fixed by https://github.com/HenrikJoreteg/key-tree-store/commit/13808f3f578982c89f4815eebf8ff869e4c5de51
